language: python
sudo: false
notifications:
  email: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install pytest pytest-cov py>=1.5.0

script:
  - python setup.py test
after_success:
  # report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
